# {%header%}

# --- {%gateway_section%} ---
gateway:
  host: localhost            # {%gateway_host%}
  port: 8010                 # {%gateway_port%}

# --- {%download_section%} ---
download:
  dir: ./download            # {%download_dir%}
  download_ori: false        # {%download_ori%}
  jpn_title: true            # {%jpn_title%}
  delete_task_files: false   # {%delete_task_files%}

# --- {%proxy_section%} ---
proxy:
  servers: []                # {%proxy_servers%}
  image: true                # {%proxy_image%}
  image_only: false          # {%proxy_image_only%}
  heal_after: 16            # {%proxy_heal_after%}

# --- {%performance_section%} ---
performance:
  scan_thread_cnt: 1         # {%scan_thread_cnt%}
  download_thread_cnt: 5     # {%download_thread_cnt%}
  async_task_concurrency: 3  # {%async_task_concurrency%}
  page_interval: 1           # {%page_interval%}
  page_retry: 3              # {%page_retry%}
  page_timeout: 10           # {%page_timeout%}
  download_retry: 5          # {%download_retry%}
  download_timeout: 8        # {%download_timeout%}

# --- {%logging_section%} ---
logging:
  path: eh.log               # {%log_path%}
  level_console: INFO        # {%log_level_console%}
  level_file: INFO           # {%log_level_file%}
