#!/usr/bin/env python
# coding:utf-8
# constants module
# Contributor:
#      fffonion        <fffonion@gmail.com>

import os
import re
import sys
import locale

# Site URL literals (hosts, URLs, host-bearing regexes) all live in site.py
from .site import (
    DOMAIN_EHENTAI,
    DOMAIN_EXHENTAI,
    DOMAIN_FORUMS_EHENTAI,
    HOST_EHENTAI,
    HOST_EXHENTAI,
    HOST_FORUMS_EHENTAI,
    LOGIN_URL,
    QUOTA_509_GIF_FRAGMENT,
    RE_STR_EHENTAI_MIGRATE,
    RE_STR_EXHENTAI_PREFIX,
    RE_STR_WEBPAGE,
    RESTR_SITE,
)

IRONPYTHON = sys.platform == 'cli'
EXEBUNDLE = getattr(sys, 'frozen', False)
LOCALE = locale.getdefaultlocale()[0]
CODEPAGE = locale.getdefaultlocale()[1] or 'ascii'
ANDROID = 'ANDROID_ARGUMENT' in os.environ

__version__ = "2.020-dy-fork.1"
DEVELOPMENT = True

SCRIPT_NAME = "xeHentai"

# https://github.com/soimort/you-get/you-get
if getattr(sys, 'frozen', False):
    # The application is frozen
    FILEPATH = os.path.dirname(os.path.realpath(sys.executable))
else:
    # The application is not frozen
    # Change this bit to match where you store your data files:
    FILEPATH = sys.path[0]

DUMMY_FILENAME = "-dummy-"
RENAME_TMPDIR = "-xeh-conflict-"

RE_INDEX = re.compile(r'.+\/(\d+)\/([^\/]+)\/*')
RE_GALLERY = re.compile(r'\/([a-f0-9]{10})\/[^\-]+\-(\d+)')
RE_IMGHASH = re.compile(r'\/([a-f0-9]{40})-(\d+)-(\d+)-(\d+)-([a-z]{,4})')
RE_FULLIMG = re.compile(r'fullimg.php\?gid=([a-z0-9]+)&page=(\d+)&key=')

RE_URL_WEBPAGE = re.compile(RE_STR_WEBPAGE)
RE_URL_IMAGE = re.compile(r'(?!%s)' % RE_STR_WEBPAGE)
# matches all
RE_URL_ALL = re.compile(r'.')

RE_LOCAL_ADDR = re.compile(r'(^localhost)|(^127\.)|(^192\.168\.)|(^10\.)|(^172\.1[6-9]\.)|(^172\.2[0-9]\.)|(^172\.3[0-1]\.)|(^::1$)|(^[fF][cCdD])')

FALLBACK_CF_IP = ("104.24.255.11", "104.24.254.11")
FALLBACK_IP_MAP = {
    DOMAIN_EHENTAI: FALLBACK_CF_IP,
    DOMAIN_FORUMS_EHENTAI: ("94.100.18.243", ),
    DOMAIN_EXHENTAI: ("217.23.13.91","217.23.13.45","109.236.84.136","109.236.92.143","109.236.84.145","109.236.92.166")
} 

DEFAULT_MAX_REDIRECTS = 30

XEH_STATE_RUNNING = 0
XEH_STATE_SOFT_EXIT = 1 # wait until current task finish and exit
XEH_STATE_FULL_EXIT = 2 # finish current task stage and exit
XEH_STATE_CLEAN = 3

TASK_STATE_PAUSED = 0
TASK_STATE_WAITING = 1
TASK_STATE_GET_META = 2
# TASK_STATE_GET_HATHDL = 3
TASK_STATE_SCAN_PAGE = 3
TASK_STATE_SCAN_IMG = 4
TASK_STATE_SCAN_ARCHIVE = 5
TASK_STATE_DOWNLOAD = 10
TASK_STATE_MAKE_ARCHIVE = 19
TASK_STATE_FINISHED = 20
TASK_STATE_FAILED = -1

TASK_STATE_ERR_URL_NOT_RECOGNIZED = -1000
TASK_STATE_ERR_CANT_DOWNLOAD_EXH = -1001
TASK_STATE_ERR_ONLY_VISIBLE_EXH = -1002
TASK_STATE_ERR_GALLERY_REMOVED = -1004
TASK_STATE_ERR_IMAGE_RESAMPLED = -1005
TASK_STATE_ERR_QUOTA_EXCEEDED = -1006
TASK_STATE_ERR_KEY_EXPIRED = -1007
TASK_STATE_ERR_NO_PAGEURL_FOUND = -1008
TASK_STATE_ERR_CONNECTION_ERROR = -1009
TASK_STATE_ERR_IP_BANNED = -1010
TASK_STATE_ERR_HATH_NOT_FOUND = -1011
TASK_STATE_ERR_IMAGE_BROKEN = -1012
TASK_STATE_ERR_SCAN_REGEX_FAILED = -1013
TASK_STATE_ERR_GALLERY_NOT_FOUND = -1014
TASK_STATE_ERR_LOGIN_REQUIRED = -1015
TASK_STATE_ERR_CANNOT_MAKE_ARCHIVE = -1301

TASK_TOP_STATUS_WAITING = 1
TASK_TOP_STATUS_PROCESSING = 2
TASK_TOP_STATUS_PROCESSED = 3


def task_top_status_name(top_status):
    return {
        TASK_TOP_STATUS_WAITING: "waiting",
        TASK_TOP_STATUS_PROCESSING: "processing",
        TASK_TOP_STATUS_PROCESSED: "processed",
    }.get(top_status, "unknown")

ERR_NO_ERROR = 0
ERR_URL_NOT_RECOGNIZED = 1000
ERR_CANT_DOWNLOAD_EXH = 1001
ERR_ONLY_VISIBLE_EXH = 1002
ERR_MALFORMED_HATHDL = 1003
ERR_GALLERY_REMOVED = 1004
ERR_IMAGE_RESAMPLED = 1005
ERR_QUOTA_EXCEEDED = 1006
ERR_KEY_EXPIRED = 1007
ERR_NO_PAGEURL_FOUND = 1008
ERR_CONNECTION_ERROR = 1009
ERR_IP_BANNED = 1010
ERR_HATH_NOT_FOUND = 1011
ERR_IMAGE_BROKEN = 1012
ERR_SCAN_REGEX_FAILED = 1013
ERR_STREAM_NOT_IMPLEMENTED = 1013

ERR_GALLERY_NOT_FOUND = 1014

ERR_TASK_NOT_FOUND = 1101
ERR_SAVE_SESSION_FAILED = 1103
ERR_TASK_LEVEL_UNDEF = 1104
ERR_DELETE_RUNNING_TASK = 1105
ERR_TASK_CANNOT_PAUSE = 1106
ERR_TASK_CANNOT_RESUME = 1107
ERR_TASK_BUSY = 1108
ERR_TASK_REFETCH_FAILED = 1109
ERR_RPC_UNAUTHORIZED = 1200
ERR_CANNOT_CREATE_DIR = 1300
ERR_CANNOT_MAKE_ARCHIVE = 1301
ERR_NOT_RANGE_FORMAT = 1302
ERR_RPC_PARSE_ERROR = -32700
ERR_RPC_INVALID_REQUEST = -32600
ERR_RPC_METHOD_NOT_FOUND = -32601
ERR_RPC_INVALID_PARAMS = -32602
ERR_RPC_EXEC_ERROR = -32603

