"""Userscript serve endpoint — serves xeh_batch.user.js with BASE_URL auto-configured."""

from fastapi import APIRouter, Request
from fastapi.responses import Response

router = APIRouter(tags=["userscript"])

# The userscript template — __BASE_URL__ will be replaced at serve time.
_USERSCRIPT_TEMPLATE = r"""// ==UserScript==
// @name         xeHentai Batch Submit
// @namespace    http://tampermonkey.net/
// @version      1.1
// @description  Batch submit e-hentai/exhentai gallery URLs to the connected xeHentai server
// @include      http*://*e-hentai.org/*
// @include      http*://exhentai.org/*
// @run-at       document-end
// @grant        GM.xmlHttpRequest
// @grant        GM.setValue
// @grant        GM.getValue
// ==/UserScript==

(async function () {
  "use strict";

  // ========= Config =========

  // Auto-generated by server — always points to the server you downloaded from
  const BASE_URL = "__BASE_URL__";

  /**
   * @typedef {Object} ConfigObject
   * @property {string} baseUrl - REST API 基地址
   * @property {{search:string, prev: number}[]} batchesHistory - 上次批量提交的搜索条件和最后一个 GID
   */

  const CONFIG_KEY = "dy.xeH.config";
  
  async function readConfig () {
    const configStr = await GM.getValue(CONFIG_KEY, null);

    /** @type {Partial<ConfigObject>} */
    const ret = {};

    try {
      if (!configStr) throw new Error("No config found");

      const config = JSON.parse(configStr);

      if (config.baseUrl && typeof config.baseUrl === "string") {
        ret.baseUrl = config.baseUrl;
      }

      if (Array.isArray(config.batchesHistory)) {
        ret.batchesHistory = config.batchesHistory
          .filter(
            (item) =>
              item &&
              typeof item.search === "string" &&
              typeof item.prev === "number",
          )
          .map((item) => ({ search: item.search, prev: item.prev }));
      }
    } catch (err) {
      console.warn("Failed to parse config, using defaults", err);
    }

    return {
      baseUrl: ret.baseUrl || BASE_URL,
      batchesHistory: ret.batchesHistory || [],
    };
  }

  /** @type {ConfigObject} */
  const config = await readConfig();

  async function saveConfig(newConfig) {
    const mergedConfig = {
      baseUrl: newConfig.baseUrl || config.baseUrl,
      batchesHistory: newConfig.batchesHistory || config.batchesHistory,
    };
    await GM.setValue(CONFIG_KEY, JSON.stringify(mergedConfig));
  }

  /** @type {(urls: string[]) => Promise<number>} */
  async function calMaxGID(urls) {
    const prev = 0;

    const max_gid = urls
      .map((url) => url.match(/g\/(\d+)\/\w+\//))
      .reduce((pv, cv) => {
        if (cv) {
          return Math.max(Number(cv[1]), pv);
        }
        return pv;
      }, prev);

    return max_gid;
  }

  /** @type {(search: URLSearchParams, prev_gid:number, setDefault?: boolean) => Promise<void>} */
  async function tryUpdateSearchHistory(search, prev_gid, setDefault = false) {
      const filtered = new URLSearchParams();
      ["f_search", "f_srdd", "f_cats"].forEach((key) => {
        if (search.has(key)) filtered.set(key, search.get(key));
      });
      const searchStr = filtered.toString();

      const existing = config.batchesHistory.find(
        (item) => item.search === searchStr,
      );

      if(existing) {
        existing.prev = prev_gid;
      }
      else if (setDefault || config.batchesHistory.length < 5) {
        config.batchesHistory.push({
          search: searchStr,
          prev: prev_gid,
        });
      }
  }

  // ========= URL Check =========

  const currentUrl = new URL(window.location.href);

  // ========= Helpers =========

  function gmRequest(details) {
    return new Promise((resolve, reject) => {
      const fn =
        typeof GM !== "undefined" && GM.xmlHttpRequest
          ? GM.xmlHttpRequest
          : GM_xmlHttpRequest;

      fn({
        ...details,
        onload: resolve,
        onerror: reject,
        ontimeout: reject,
      });
    });
  }

  async function submitTask(url) {
    const response = await gmRequest({
      method: "POST",
      url: `${BASE_URL}/api/tasks`,
      headers: {
        "Content-Type": "application/json",
      },
      data: JSON.stringify({ url }),
    });

    let json;

    try {
      json = JSON.parse(response.responseText);
    } catch (err) {
      throw new Error(`Invalid JSON response for ${url}`);
    }

    return json;
  }

  async function submitBulkTasks(urls) {
    const response = await gmRequest({
      method: "POST",
      url: `${BASE_URL}/api/tasks/bulk`,
      headers: {
        "Content-Type": "application/json",
      },
      data: JSON.stringify({ urls }),
    });

    let json;

    try {
      json = JSON.parse(response.responseText);
    } catch (err) {
      throw new Error("Invalid JSON response for bulk submission");
    }

    return json;
  }

  function getCurrentGalleryUrl() {
    return `${currentUrl.origin}${currentUrl.pathname}`;
  }

  function getBatchGalleryUrls() {
    let urls = [...document.querySelectorAll("td.glname")]
      .map((td) => td.querySelector("a[href]"))
      .filter((node) => node && node.href)
      .map((a) => a.href);

    if (urls.length > 0) {
      return urls;
    }

    urls = [...document.querySelectorAll("td.gl1e")]
      .map((td) => td.querySelector("a[href]"))
      .filter((node) => node && node.href)
      .map((a) => a.href);

    if (urls.length > 0) {
      return urls;
    }

    return [...document.querySelectorAll("div.gl1t")]
      .map((td) => td.querySelector("a[href]"))
      .filter((node) => node && node.href)
      .map((a) => a.href);
  }

  /**
   * @typedef {Object} PageAction
   * @property {(current_url: URL) => boolean} filter - Function to determine if the action applies to the current page
   * @property {() => Promise<void>} action - Function to execute when the action is triggered
   * @property {string} tooltip - Tooltip text for the action button
   * @property {string} buttonSymbol - Symbol to display on the action button
   */

  /** @type {PageAction[]} */
  const pageActions = [
    {
      filter: (current_url) => {
        return current_url.pathname === "/" || currentUrl.pathname.startsWith("/tag/")
      },
      buttonSymbol: "\u21E9",
      action: async () => {
        const urls = getBatchGalleryUrls();
        await submitBulkTasks(urls);
        const uprev = document.getElementById("uprev");
        const current_search = new URLSearchParams(window.location.search);
        if (current_search.has("f_search")) {
          const prev_gid = await calMaxGID(urls);
          await tryUpdateSearchHistory(current_search, prev_gid);
          await saveConfig({ batchesHistory: config.batchesHistory });
        }
        const href = uprev?.getAttribute("href");
        if (!href) return;
        uprev.click();
      },
      tooltip: "\u53D1\u9001\u5F53\u524D\u641C\u7D22\u7ED3\u679C\u5217\u8868\u4E2D\u7684\u6240\u6709\u753B\u5ECA\u5230\u4E0B\u8F7D\u670D\u52A1",
    },
    {
      filter: (current_url) =>
        /^\/g\/\d+\/[0-9a-fA-F]{10}\//.test(current_url.pathname),
      buttonSymbol: "\u21E9",
      action: async () => {
        const galleryUrl = getCurrentGalleryUrl();
        await submitTask(galleryUrl);
        console.log(`Task submitted: ${galleryUrl}`);
      },
      tooltip: "\u53D1\u9001\u5F53\u524D\u753B\u5ECA\u5230\u4E0B\u8F7D\u670D\u52A1",
    },
  ];

  const matchedAction = pageActions.find((action) => action.filter(currentUrl));

  function buildRestoreUrl(historyItem) {
    const targetUrl = new URL("/", currentUrl.origin);
    const params = new URLSearchParams(historyItem.search);
    params.set("prev", String(historyItem.prev));
    targetUrl.search = params.toString();
    return targetUrl.toString();
  }

  function createHoverTooltipWrapper(triggerElement, tooltipText) {
    const wrapper = document.createElement("div");
    wrapper.className = "xeh-hover-wrap";

    Object.assign(wrapper.style, {
      position: "relative",
      display: "inline-block",
    });

    const tooltip = document.createElement("div");
    tooltip.className = "xeh-hover-tooltip";
    tooltip.textContent = tooltipText;

    Object.assign(tooltip.style, {
      position: "absolute",
      left: "calc(100% + 12px)",
      top: "50%",
      transform: "translateY(-50%)",
      padding: "8px 12px",
      borderRadius: "6px",
      background: "rgba(0,0,0,0.75)",
      color: "#fff",
      fontSize: "13px",
      lineHeight: "1.3",
      pointerEvents: "none",
      whiteSpace: "nowrap",
      boxShadow: "0 2px 8px rgba(0,0,0,0.3)",
    });

    wrapper.appendChild(triggerElement);
    wrapper.appendChild(tooltip);

    return wrapper;
  }

  function renderHistoryPanel() {
    const oldPanel = document.getElementById("xeh-history-panel");
    if (oldPanel) {
      oldPanel.remove();
    }

    const panel = document.createElement("div");
    panel.id = "xeh-history-panel";
    panel.className = "xeh-history-panel";

    Object.assign(panel.style, {
      position: "fixed",
      left: "20px",
      top: "20px",
      zIndex: "999999",
      display: "flex",
      flexDirection: "column",
      gap: "8px",
      alignItems: "stretch",
    });

    config.batchesHistory.forEach((item, index) => {
      const historyBtn = document.createElement("button");
      historyBtn.textContent = `\u8FD8\u539F\u641C\u7D22\u9875${index + 1}`;
      historyBtn.title = "\u957F\u6309\u5220\u9664";

      Object.assign(historyBtn.style, {
        border: "1px solid #2f4f4f",
        borderRadius: "8px",
        padding: "6px 10px",
        width: "130px",
        background: "#f5f7fa",
        color: "#1f2d3d",
        fontSize: "13px",
        cursor: "pointer",
        textAlign: "center",
        boxShadow: "0 1px 3px rgba(0,0,0,0.2)",
      });

      let isDeleteMode = false;
      let suppressClickOnce = false;
      let longPressTimer = null;

      const enterDeleteMode = () => {
        isDeleteMode = true;
        suppressClickOnce = true;
        historyBtn.textContent = "\u5220\u9664";
        historyBtn.title = "\u70B9\u51FB\u5220\u9664";
        historyBtn.style.background = "#d32f2f";
        historyBtn.style.color = "#fff";
        historyBtn.style.borderColor = "#9a1f1f";
      };

      const startLongPress = () => {
        if (isDeleteMode) {
          return;
        }
        longPressTimer = window.setTimeout(enterDeleteMode, 650);
      };

      const cancelLongPress = () => {
        if (longPressTimer !== null) {
          window.clearTimeout(longPressTimer);
          longPressTimer = null;
        }
      };

      historyBtn.addEventListener("mousedown", startLongPress);
      historyBtn.addEventListener("mouseup", cancelLongPress);
      historyBtn.addEventListener("mouseleave", cancelLongPress);
      historyBtn.addEventListener("mouseenter", () => {
        historyBtn.title = isDeleteMode ? "\u70B9\u51FB\u5220\u9664" : "\u957F\u6309\u5220\u9664";
      });
      historyBtn.addEventListener("touchstart", startLongPress, { passive: true });
      historyBtn.addEventListener("touchend", cancelLongPress);
      historyBtn.addEventListener("touchcancel", cancelLongPress);

      historyBtn.addEventListener("click", async () => {
        if (suppressClickOnce) {
          suppressClickOnce = false;
          return;
        }

        if (isDeleteMode) {
          config.batchesHistory.splice(index, 1);
          await saveConfig({ batchesHistory: config.batchesHistory });
          renderHistoryPanel();
          return;
        }

        window.location.href = buildRestoreUrl(item);
      });

      const historyItemWrapper = createHoverTooltipWrapper(historyBtn, item.search + `&prev=${item.prev}`);
      Object.assign(historyItemWrapper.style, {
        display: "block",
      });

      panel.appendChild(historyItemWrapper);
    });

    const saveBtn = document.createElement("button");
    saveBtn.textContent = "\u4FDD\u5B58\u641C\u7D22";
    saveBtn.title = "\u5C06\u5F53\u524D\u641C\u7D22\u6761\u4EF6\u548C\u6700\u65B0 prev \u4FDD\u5B58\u5230\u5386\u53F2";

    Object.assign(saveBtn.style, {
      border: "1px solid #0b5cab",
      borderRadius: "8px",
      padding: "7px 10px",
      background: "#1976d2",
      color: "#fff",
      fontSize: "13px",
      cursor: "pointer",
      textAlign: "center",
      boxShadow: "0 1px 3px rgba(0,0,0,0.25)",
    });

    saveBtn.addEventListener("click", async () => {
      const currentSearch = new URLSearchParams(window.location.search);

      if (!currentSearch.has("f_search")) {
        alert("\u5F53\u524D\u9875\u9762\u6CA1\u6709 f_search \u53C2\u6570\uFF0C\u65E0\u6CD5\u4FDD\u5B58\u3002\n\u8BF7\u5148\u8FDB\u5165\u641C\u7D22\u7ED3\u679C\u9875\u3002");
        return;
      }

      if (!currentSearch.has("prev")) {
        alert("\u5F53\u524D\u9875\u9762\u6CA1\u6709 prev \u53C2\u6570\uFF0C\u65E0\u6CD5\u4FDD\u5B58\u3002\n\u8BF7\u5148\u70B9\u51FB\u641C\u7D22\u7ED3\u679C\u5217\u8868\u9875\u7684\u4E0B\u4E00\u9875\uFF0C\u786E\u4FDD URL \u4E2D\u6709 prev \u53C2\u6570\u3002");
        return;
      }

      const urls = getBatchGalleryUrls();

      if (urls.length === 0) {
        alert("\u5F53\u524D\u9875\u9762\u6CA1\u6709\u53EF\u7528\u7684\u753B\u5ECA\u5217\u8868\uFF0C\u65E0\u6CD5\u4FDD\u5B58\u3002\n\u8BF7\u5728\u641C\u7D22\u7ED3\u679C\u5217\u8868\u9875\u70B9\u51FB\u4FDD\u5B58\u3002");
        return;
      }

      saveBtn.disabled = true;
      const originalText = saveBtn.textContent;
      saveBtn.textContent = "\u4FDD\u5B58\u4E2D...";

      const prev_gid = parseInt(currentSearch.get("prev"), 10);

      try {
        await tryUpdateSearchHistory(currentSearch, prev_gid, true);
        await saveConfig({ batchesHistory: config.batchesHistory });
        renderHistoryPanel();
      } catch (err) {
        console.error(err);
        alert(`\u4FDD\u5B58\u5931\u8D25: ${err}`);
        saveBtn.textContent = originalText;
      } finally {
        saveBtn.disabled = false;
      }
    });

    panel.appendChild(saveBtn);
    document.body.appendChild(panel);
  }

  if(currentUrl.pathname === "/") {
    renderHistoryPanel();
  }

  if (!matchedAction) {
    return;
  }

  // ========= Floating Button =========

  const wrapper = document.createElement("div");
  wrapper.className = "xeh-batch-wrapper";

  Object.assign(wrapper.style, {
    position: "fixed",
    left: "20px",
    bottom: "20px",
    zIndex: "999999",
  });

  const button = document.createElement("button");
  const buttonSymbol = matchedAction.buttonSymbol;
  button.className = "xeh-batch-btn";

  button.textContent = buttonSymbol;

  Object.assign(button.style, {
    width: "56px",
    height: "56px",
    borderRadius: "50%",
    border: "none",
    background: "#1976d2",
    color: "#fff",
    fontSize: "24px",
    cursor: "pointer",
    boxShadow: "0 2px 8px rgba(0,0,0,0.35)",
  });

  const buttonWithTooltip = createHoverTooltipWrapper(button, `${matchedAction.tooltip}`);
  Object.assign(buttonWithTooltip.style, {
    position: "relative",
    display: "inline-block",
  });

  wrapper.appendChild(buttonWithTooltip);
  document.body.appendChild(wrapper);

  const style = document.createElement("style");
  style.textContent = `
        .xeh-hover-tooltip {
            opacity: 0;
            visibility: hidden;
            transition: opacity 0.12s ease;
        }

        .xeh-hover-wrap:hover .xeh-hover-tooltip {
            opacity: 1;
            visibility: visible;
        }
    `;
  document.head.appendChild(style);

  // ========= Main =========

  button.addEventListener("click", async () => {
    button.disabled = true;
    button.textContent = "...";

    try {
      await matchedAction.action();
    } catch (err) {
      console.error(err);
      alert(`Failed: ${err}`);
    } finally {
      button.disabled = false;
      button.textContent = buttonSymbol;
    }
  });
})();
"""


def _build_base_url(request: Request) -> str:
    """Derive the server's base URL from the incoming request.

    Uses the Host header when available, falling back to the configured
    webui_host:webui_port from xeH config."""
    xeH = request.app.state.xeH
    host = request.headers.get("Host") or request.headers.get("host") or ""
    if host:
        scheme = "https" if request.url.scheme == "https" else "http"
        return f"{scheme}://{host}"
    # Fallback to configured address
    cfg_host = xeH.config.get("webui_host", "localhost")
    cfg_port = xeH.config.get("webui_port") or 8010
    return f"http://{cfg_host}:{cfg_port}"


@router.get("/userscript/xeh_batch.user.js", response_class=Response)
async def serve_userscript(request: Request):
    """Serve the userscript with BASE_URL set to this server's address."""
    base_url = _build_base_url(request)
    content = _USERSCRIPT_TEMPLATE.replace("__BASE_URL__", base_url)
    return Response(
        content=content,
        media_type="application/javascript; charset=utf-8",
    )
